# Generated by Django 2.0.4 on 2018-04-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('photo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('volume', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('rating', models.FloatField(max_length=1)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('age_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('rating', models.FloatField(max_length=1)),
                ('poster', models.CharField(max_length=250)),
                ('header', models.CharField(max_length=250)),
                ('author', models.ManyToManyField(to='manga.Author')),
                ('genre', models.ManyToManyField(to='manga.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='manga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.Manga'),
        ),
    ]
