# Generated by Django 2.0.4 on 2018-04-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='poster',
            field=models.ImageField(blank=True, upload_to='upload/manga/<django.db.models.fields.CharField>/', verbose_name=models.CharField(max_length=250)),
        ),
    ]
